name = "asdf_prune"
version = "1.0.0"
description = "Clean up asdf packages"
licences = ["MIT"]
repository = { type = "github", user = "nikosl", repo = "asdf_prune" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
spinner = ">= 1.1.0 and < 2.0.0"
snag = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.3.0 and < 2.0.0"
birdie = ">= 1.1.6 and < 2.0.0"
